channels:
  - conda-forge
  - defaults
dependencies:
  - brian2
  - ipykernel
  - matplotlib
  - seaborn
  - numpy=1.24
  - pandas
  - scipy
  - networkx
  - pyarrow
  - xlsxwriter
  - openpyxl
  - joblib
  - jupyter
  - jupyterlab
